spring:
  ai:
    mcp:
      client:
        sse:
          connections:
            server1:
              url:http://localhost:8127
        # 以下是通过SSE方式
#         stdio:
#            servers-configuration: classpath:mcp-servers.json
    dashscope:
      api-key: your-apikey
      chat:
        options:
          model: glm-5.1
  application:
    name: ai-agent
  profiles:
    active: local

  mail:
    host: smtp.qq.com
    port: 465
    username: 你的邮箱@qq.com
    password: 你的SMTP授权码
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
#    基于pgsql的向量数据库存储
#    vectorstore:
#      pgvector:
#        index-type: HNSW
#        dimensions: 1024
#        distance-type: cosine-distance
#        max-document-batch-size: 10000
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.itheima.aiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8123
  servlet:
    context-path: /api
# search API
search-api:
  api-key: your_api_key
# 修改输出日志的级别
logging:
  level:
    org.springframework.ai: DEBUG